### ISSUE TITLE
Panic when dropping items and switching slots

### ISSUE THREAD

**Issue by Wazner** [feather-rs/feather#176]
I have found a reproducable way to create a panic inside the server.

It seems that the same resource `EntityInventory` is borrowed two times simultaneously. Once in the [`handle_held_item_change`](https://github.com/feather-rs/feather/blob/6895f444008d73909d60958ee03065f8702b34eb/server/src/packet_handlers/inventory.rs#L90) system and once in the [`handle_player_digging`](https://github.com/feather-rs/feather/blob/6895f444008d73909d60958ee03065f8702b34eb/server/src/packet_handlers/digging.rs#L21) system.
I find this odd seeing as legion (or tonks?) should have prevented these systems from running at the same time (due to the `Write<EntityInventory>` requirement).

**System**
Commit: 6895f444008d73909d60958ee03065f8702b34eb
OS: Ubuntu
Architecture: x64

*The panic only happens in DEBUG build, but the double mutable borrow still happens in RELEASE builds. Some logging showing this behaviour:*
```
2020-02-23 12:12:25,627 DEBUG [feather_server::packet_handlers::inventory] borrowing inventory
2020-02-23 12:12:25,627 DEBUG [feather_server::packet_handlers::digging] borrowing inventory
2020-02-23 12:12:25,627 DEBUG [feather_server::packet_handlers::inventory] ending borrow
2020-02-23 12:12:25,627 WARN  [feather_server::packet_handlers::digging] Unhandled Player Digging status DropItem
2020-02-23 12:12:25,627 DEBUG [feather_server::packet_handlers::digging] ending borrow
```

**Steps to reproduce**
1. Join the world
2. Spam the drop item key (Q) all the while scrolling to switch item slots

![Peek 2020-02-22 21-34](https://user-images.githubusercontent.com/1642535/75098851-68940d80-55bb-11ea-8b52-9bd798070772.gif)

**Stack trace**
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "resource already borrowed as mutable"', legion/src/borrow.rs:121:42
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at backtrace/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1199
  14: core::result::Result<T,E>::unwrap
             at rustc/src/libcore/result.rs:963
  15: legion::borrow::AtomicRefCell<T>::get_mut
             at legion/src/borrow.rs:121
  16: legion::storage::ComponentResourceSet::data_raw_mut
             at legion/src/storage.rs:1389
  17: legion::storage::ComponentResourceSet::data_slice_mut
             at legion/src/storage.rs:1423
  18: legion::world::World::get_component_mut_unchecked
             at legion/src/world.rs:571
  19: tonks::query::PreparedWorld::get_component_mut_unchecked
             at tonks/src/query.rs:113
  20: tonks::query::PreparedWorld::get_component_mut
             at tonks/src/query.rs:96
  21: <feather_server::packet_handlers::inventory::handle_held_item_change as tonks::system::System>::run
             at server/src/packet_handlers/inventory.rs:105
  22: <tonks::system::CachedSystem<S> as tonks::system::RawSystem>::execute_raw
             at tonks/src/system.rs:141
  23: tonks::scheduler::Scheduler::dispatch_stage::{{closure}}::{{closure}}
             at tonks/src/scheduler/mod.rs:658
  24: core::iter::traits::iterator::Iterator::try_fold
             at rustc/src/libcore/iter/traits/iterator.rs:1876
  25: core::iter::traits::iterator::Iterator::fold
             at rustc/src/libcore/iter/traits/iterator.rs:2003
  26: core::iter::traits::iterator::Iterator::for_each
             at rustc/src/libcore/iter/traits/iterator.rs:659
  27: <rayon::iter::for_each::ForEachConsumer<F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at rayon/src/iter/for_each.rs:55
  28: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at rayon/src/iter/map.rs:248
  29: rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon/src/iter/plumbing/mod.rs:438
  30: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon/src/iter/plumbing/mod.rs:418
  31: rayon_core::join::join_context::call_a::{{closure}}
             at rayon-core/src/join/mod.rs:125
  32: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/src/libstd/panic.rs:318
  33: std::panicking::try::do_call
             at rustc/src/libstd/panicking.rs:303
  34: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  35: std::panicking::try
             at rustc/src/libstd/panicking.rs:281
  36: std::panic::catch_unwind
             at rustc/src/libstd/panic.rs:394
  37: rayon_core::unwind::halt_unwinding
             at rayon-core/src/unwind.rs:17
  38: rayon_core::join::join_context::{{closure}}
             at rayon-core/src/join/mod.rs:146
  39: rayon_core::registry::in_worker
             at rayon-core/src/registry.rs:799
  40: rayon_core::join::join_context
             at rayon-core/src/join/mod.rs:133
  41: rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon/src/iter/plumbing/mod.rs:416
  42: rayon::iter::plumbing::bridge_producer_consumer
             at rayon/src/iter/plumbing/mod.rs:397
  43: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at rayon/src/slice/mod.rs:487
  44: rayon::iter::plumbing::bridge
             at rayon/src/iter/plumbing/mod.rs:357
  45: rayon::iter::for_each::for_each
             at rayon/src/iter/for_each.rs:12
  46: rayon::iter::ParallelIterator::for_each
             at rayon/src/iter/mod.rs:362
  47: tonks::scheduler::Scheduler::dispatch_stage::{{closure}}
             at tonks/src/scheduler/mod.rs:648
  48: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/src/libstd/panic.rs:318
  49: std::panicking::try::do_call
             at rustc/src/libstd/panicking.rs:303
  50: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  51: std::panicking::try
             at rustc/src/libstd/panicking.rs:281
  52: std::panic::catch_unwind
             at rustc/src/libstd/panic.rs:394
  53: rayon_core::unwind::halt_unwinding
             at rayon-core/src/unwind.rs:17
  54: rayon_core::spawn::spawn_job::{{closure}}
             at rayon-core/src/spawn/mod.rs:98
  55: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
             at rayon-core/src/job.rs:167
  56: rayon_core::registry::WorkerThread::execute
             at rayon-core/src/registry.rs:681
  57: rayon_core::registry::WorkerThread::wait_until_cold
             at rayon-core/src/registry.rs:665
  58: rayon_core::registry::WorkerThread::wait_until
             at rayon-core/src/registry.rs:639
  59: rayon_core::join::join_context::{{closure}}
             at rayon-core/src/join/mod.rs:180
  60: rayon_core::registry::in_worker
             at rayon-core/src/registry.rs:799
  61: rayon_core::join::join_context
             at rayon-core/src/join/mod.rs:133
  62: rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon/src/iter/plumbing/mod.rs:416
  63: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon/src/iter/plumbing/mod.rs:427
  64: rayon_core::join::join_context::call_b::{{closure}}
             at rayon-core/src/join/mod.rs:130
  65: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::call::{{closure}}
             at rayon-core/src/job.rs:113
  66: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/src/libstd/panic.rs:318
  67: std::panicking::try::do_call
             at rustc/src/libstd/panicking.rs:303
  68: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  69: std::panicking::try
             at rustc/src/libstd/panicking.rs:281
  70: std::panic::catch_unwind
             at rustc/src/libstd/panic.rs:394
  71: rayon_core::unwind::halt_unwinding
             at rayon-core/src/unwind.rs:17
  72: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
             at rayon-core/src/job.rs:119
  73: rayon_core::registry::WorkerThread::execute
             at rayon-core/src/registry.rs:681
  74: rayon_core::registry::WorkerThread::wait_until_cold
             at rayon-core/src/registry.rs:665
  75: rayon_core::registry::WorkerThread::wait_until
             at rayon-core/src/registry.rs:639
  76: rayon_core::join::join_context::{{closure}}
             at rayon-core/src/join/mod.rs:180
  77: rayon_core::registry::in_worker
             at rayon-core/src/registry.rs:799
  78: rayon_core::join::join_context
             at rayon-core/src/join/mod.rs:133
  79: rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon/src/iter/plumbing/mod.rs:416
  80: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon/src/iter/plumbing/mod.rs:418
  81: rayon_core::join::join_context::call_a::{{closure}}
             at rayon-core/src/join/mod.rs:125
  82: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/src/libstd/panic.rs:318
  83: std::panicking::try::do_call
             at rustc/src/libstd/panicking.rs:303
  84: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  85: std::panicking::try
             at rustc/src/libstd/panicking.rs:281
  86: std::panic::catch_unwind
             at rustc/src/libstd/panic.rs:394
  87: rayon_core::unwind::halt_unwinding
             at rayon-core/src/unwind.rs:17
  88: rayon_core::join::join_context::{{closure}}
             at rayon-core/src/join/mod.rs:146
  89: rayon_core::registry::in_worker
             at rayon-core/src/registry.rs:799
  90: rayon_core::join::join_context
             at rayon-core/src/join/mod.rs:133
  91: rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon/src/iter/plumbing/mod.rs:416
  92: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at rayon/src/iter/plumbing/mod.rs:418
  93: rayon_core::join::join_context::call_a::{{closure}}
             at rayon-core/src/join/mod.rs:125
  94: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/src/libstd/panic.rs:318
  95: std::panicking::try::do_call
             at rustc/src/libstd/panicking.rs:303
  96: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  97: std::panicking::try
             at rustc/src/libstd/panicking.rs:281
  98: std::panic::catch_unwind
             at rustc/src/libstd/panic.rs:394
  99: rayon_core::unwind::halt_unwinding
             at rayon-core/src/unwind.rs:17
 100: rayon_core::join::join_context::{{closure}}
             at rayon-core/src/join/mod.rs:146
 101: rayon_core::registry::in_worker
             at rayon-core/src/registry.rs:799
 102: rayon_core::join::join_context
             at rayon-core/src/join/mod.rs:133
 103: rayon::iter::plumbing::bridge_producer_consumer::helper
             at rayon/src/iter/plumbing/mod.rs:416
 104: rayon::iter::plumbing::bridge_producer_consumer
             at rayon/src/iter/plumbing/mod.rs:397
 105: <rayon::slice::Iter<T> as rayon::iter::IndexedParallelIterator>::with_producer
             at rayon/src/slice/mod.rs:487
 106: rayon::iter::plumbing::bridge
             at rayon/src/iter/plumbing/mod.rs:357
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Rayon: detected unexpected panic; aborting
Aborted (core dumped)
```

**Comment by caelunshun** [comment]
Thanks for reporting! I've stumbled upon this bug a few times as well—it's most likely a bug in `tonks` lurking around somewhere. The reason it doesn't happen in release mode is because Legion disables runtime borrow checking when optimizations are on—so when running in release mode, there is undefined behavior. I've opened an issue in `tonks` to fix this.

**Comment by caelunshun** [comment]
Found one bug in tonks, but the issue still persists. I'll keep looking...

**Comment by Wazner** [comment]
I took a shot at fixing this bug this evening, after adding trace logging everywhere I found the cause of the bug. Stage dependencies were not filled correctly.

I created a Pull Request on the `tonks` repository.
