### ISSUE TITLE
Crash when player go under the map

### ISSUE THREAD

**Issue by besuper** [feather-rs/feather#204]
It's a small thing but it's make the server crashing. When a player go below 0 the server crash.

```thread 'main' panicked at 'assertion failed: y < CHUNK_HEIGHT', core/chunk/src/lib.rs:333:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: std::panicking::begin_panic
  12: feather_chunk::Chunk::block_at
  13: feather_chunk_map::ChunkMap::block_at
  14: feather_server_types::game::Game::block_at
  15: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
  16: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
  17: <feather_server_util::block::on_block_update_notify_adjacent as fecs::events::RawEventHandler>::handle
  18: feather_server_types::game::Game::set_block_at
  19: feather_server_player::packet_handlers::digging::handle_digging
  20: <T as feather_server_player::packet_handlers::IteratorExt>::for_each_valid
  21: <feather_server_player::packet_handlers::digging::handle_player_digging as fecs::system::RawSystem>::run
  22: feather_server::run_loop
  23: feather_server::main::{{closure}}
  24: <std::future::GenFuture<T> as core::future::future::Future>::poll
  25: tokio::runtime::enter::Enter::block_on
  26: tokio::runtime::context::enter
  27: tokio::runtime::Runtime::block_on
  28: feather_server::main
  29: std::rt::lang_start::{{closure}}
  30: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  31: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  32: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  33: std::panicking::try
             at src/libstd/panicking.rs:281
  34: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  35: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  36: main
  37: __libc_start_main
  38: _start```

**Comment by caelunshun** [comment]
Fixed, thanks!
